name: Beta Push
concurrency:
  group: betapush
on:
  push:
    branches:
      - beta
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.PAT_GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn release