name: Pull Request
on: pull_request
jobs:
  lint-build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn check
